[package]
name = "viewer3d"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.38", features = ["derive"] }
pars3d = { git = "https://github.com/JulianKnodt/pars3d.git", version = "0.1.0" }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
wgpu = "25.0.0"
winit = "0.30.10"
